### ISSUE TITLE
Add missing license file

### ISSUE THREAD

**Issue by 0x326** [cazinge/CourseJS#11]
This project is missing a license file, which is necessary for others to build upon this repo in compliance with the U.S. Copyright Law.  I would highly suggest the MIT license, the BSD 2-clause license, the BSD 3-clause, the ISC license, or the Apache 2.0 license.  However, I would strongly recommend against a "copyleft" license such as the GNU GPL since such licenses are harmful to businesses by design and they do not reflect the true spirit of open source software.  

If one creates a file named `LICENSE` from the GitHub web interface, most of the above licenses are available as quick templates.

**Comment by azinge** [comment]
MIT license has been added, thank you for bringing that to my attention.
